# fly.toml app configuration file for harmony-llm-api

app = "harmony-llm-api-dev"
primary_region = "den"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source="llm_api_data_dev"
  destination="/data"

[env]
  FLASK_APP = "main.py"
  FLASK_ENV = "test"

[deploy]
  release_command = "flask db upgrade"


# app = "harmony-llm-api-dev"
# primary_region = "den"

# [build]

# [http_service]
#   internal_port = 8080
#   force_https = true
#   auto_stop_machines = "stop"
#   auto_start_machines = true
#   min_machines_running = 1
#   processes = ["app"]

# [mounts]
#   source="llm_api_data_dev"
#   destination="/data"
